import frida, time, subprocess, json
def sh(*a): return subprocess.run(list(a), capture_output=True, text=True)
r = sh("adb","-s","localhost:5555","shell","pidof","com.snake")
if not r.stdout.strip():
    sh("adb","-s","localhost:5555","shell","am","start","-n","com.snake/com.Entry"); time.sleep(16)
    r = sh("adb","-s","localhost:5555","shell","pidof","com.snake")
pid = int(r.stdout.strip().split()[0])
print("[*] PID:", pid)
device = frida.get_device_manager().add_remote_device("localhost:27042")
session = device.attach(pid)
script = session.create_script(open("/tmp/agent_callbacks.js").read())
script.load()
res = script.exports_sync.readcallbacks()
print("[*] base=%s" % res.get("base"))
print("[*] structPtr=%s begin=%s end=%s count=%s err=%s" % (res.get("structPtr"),res.get("begin"),res.get("end"),res.get("count"),res.get("err")))
print("\n=== DISPATCHER CALLBACK LIST ===")
for c in res.get("callbacks",[]):
    print("  cb[%02d] -> %s  engOff=%s" % (c["idx"], c["ptr"], c.get("engOff")))
with open("/tmp/callbacks.json","w") as f: json.dump(res,f,indent=2)
print("\n[*] saved /tmp/callbacks.json")
session.detach()
